config/routes.rb
Rails.application.routes.draw do
  root to: "restaurants#index"

  devise_for :users

  resources :restaurants, only: [:index] do
    resource :stars, only: [:create, :destroy]
  end
  resources :reservations, only: [:create]

  namespace :admin do
    resources :restaurants
    resources :stars
    resources :users

    root to: "restaurants#index"
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  validates_presence_of :email, :eta, :party_size, :restaurant

  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates_presence_of :name

  has_many :reservations
  has_many :stars
  has_many :fans, through: :stars, source: :user
  belongs_to :owner, class_name: "User"
end

app/models/star.rb
class Star < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  USER_ROLES = %w(patron owner)
  private_constant :USER_ROLES

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_inclusion_of :role, in: USER_ROLES
  validates_presence_of :role

  has_many :restaurants, foreign_key: :owner_id
  has_many :stars
  has_many :starred_restaurants, through: :stars, source: :restaurant

  def owner?
    role == "owner"
  end

  def has_starred?(restaurant)
    starred_restaurants.include?(restaurant)
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_owner

    def authenticate_owner
      current_user.owner?
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/restaurants_controller.rb
module Admin
  class RestaurantsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    def index
      super
      @resources = current_user.restaurants
    end

    def resource_params
      super.merge(owner_id: current_user.id)
    end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/stars_controller.rb
module Admin
  class StarsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    def index
      super
      @resources = current_user.
        restaurants.
        includes(:stars).
        flat_map(&:stars)
    end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Star.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    def index
      super
      @resources = current_user.
        restaurants.
        includes(:fans).
        flat_map(&:fans)
    end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create
    reservation = Reservation.new(reservation_params)
    restaurant = reservation.restaurant

    if reservation.save
      flash[:sucess] = t("flash.reservations.success")
      ReservationsMailer.
        confirmation(receiver: restaurant.owner.email, restaurant: restaurant).
        deliver_later
    else
      flash[:error] = t("flash.reservations.error")
    end

    redirect_to restaurants_path
  end

  private

  def reservation_params
    params.
      require(:reservation).
      permit(:restaurant_id, :name, :email, :party_size, :eta)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    render locals: {
      restaurants: Restaurant.all
    }
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  layout false

  def create
    restaurant = Restaurant.find(params[:restaurant_id])
    restaurant.fans << current_user

    render locals: {
      restaurants: Restaurant.all
    }
  end

  def destroy
    restaurant = Restaurant.find(params[:restaurant_id])
    restaurant.fans.delete(current_user)

    render locals: {
      restaurants: Restaurant.all
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.slim
#flash
  - flash.each do |key, value|
    .flash class="flash-#{key}" = value

app/views/application/_javascript.slim
= javascript_include_tag :application

= yield :javascript

- if Rails.env.test?
  javascript:
    $.fx.off = true;
    $.ajaxSetup({ async: false });

app/views/application/_navbar.slim
- if signed_in?
  = render "refills/navigation"
- else
  .TopLinks
    = link_to t("navigation.sign_in"), new_user_session_path, class: "TopLinks-link"
  .u-pushTop

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="ROBOTS" content="NOODP"
    title Reserver
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    link href="http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic" rel="stylesheet" type="text/css"
    = stylesheet_link_tag :application, media: "all"
    = render "javascript"
    = csrf_meta_tags
  body
    = render "flashes"
    = render "navbar"
    .Layout
      .Layout-content
        = yield

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>

app/views/refills/_navigation.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <%= link_to root_path, class: "logo" do %>
      <%= image_tag "logo.png", alt: "Logo Image" %>
    <% end %>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <div class="navigation-tools">
      <nav role="navigation">
        <ul id="js-navigation-menu" class="navigation-menu show">
          <li class="nav-link more"><a href="javascript:void(0)"><%= current_user.email %></a>
            <ul class="submenu">
              <% if current_user.owner? %>
                <li>
                  <%= link_to admin_root_path do %>
                    <%= t("navigation.dashboard") %>
                  <% end %>
                </li>
              <% end %>

              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <%= t("navigation.log_out") %>
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/reservations/_new.slim
.modal
  input.modal-state id="#{modal_id}" type="checkbox"
  .modal-window
    .modal-inner
      label.modal-close for="#{modal_id}"
      h1 = t("reservations.new.title", restaurant: restaurant.name)
      .modal-content
        = form_for :reservation, url: reservations_path do |form|
          = form.hidden_field :restaurant_id, value: restaurant.id

          = form.label :name
          = form.text_field :name

          = form.label :email
          = form.text_field :email

          = form.label :party_size
          = form.number_field :party_size

          = form.label :eta
          = form.date_field :eta

          = form.submit

app/views/restaurants/_list.slim
ul#restaurants
  - restaurants.each do |restaurant|
    li.Restaurant
      .Restaurant-name = restaurant.name
      - modal_id = "reservation-modal-#{dom_id(restaurant)}"
      = link_to "#" do
        = label_tag modal_id do
          .modal-trigger = t("restaurants.reserve")
      = render "reservations/new", restaurant: restaurant, modal_id: modal_id
      - if signed_in?
        = render "stars/starring", restaurant: restaurant

app/views/restaurants/index.slim
.Container.Container--centered.u-pushTop
  h1.Title = t("restaurants.title")

= render "restaurants/list", restaurants: restaurants

app/views/stars/_starring.slim
.Restaurant-action
  - if current_user.has_starred?(restaurant)
    = link_to "unstar", restaurant_stars_path(restaurant), method: :delete, remote: true
  - else
    = link_to "star", restaurant_stars_path(restaurant), method: :post, remote: true

app/views/stars/create.js.erb
$("#restaurants").replaceWith("<%= escape_javascript(render("restaurants/list", restaurants: restaurants)) %>")

app/views/stars/destroy.js.erb
$("#restaurants").replaceWith("<%= escape_javascript(render("restaurants/list", restaurants: restaurants)) %>")